---
repos:
  - repo: https://github.com/PyCQA/doc8.git
    rev: 0.10.1
    hooks:
      - id: doc8
  - repo: https://github.com/python/black.git
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>=5.1.1
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
        language_version: python3
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        exclude: ^molecule_digitalocean/cookiecutter/{{cookiecutter.molecule_directory}}
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
        args: ["-L", "keypair"]
        require_serial: false
        additional_dependencies: []
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.3.1
    hooks:
      - id: ansible-lint
